apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-github
  namespace: kubeflow
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  type: Python
  mode: cluster
  image: gcr.io/spark-operator/spark-py:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: https://raw.githubusercontent.com/reddyprasadaviso/ds-spark-jobs/dev/pi.py
  sparkVersion: 3.1.1
  restartPolicy:
    type: Never
  deps: {}
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-controller
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
  executor:
    cores: 1
    instances: 2
    memory: 512m
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
