apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-github
  namespace: kubeflow
  labels:
    version: "1.0"
spec:
  type: Scala
  mode: cluster
  image: gcr.io/spark-operator/spark:v3.4.1
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.4.1.jar
  sparkVersion: "3.4.1"
  restartPolicy:
    type: Never
  sparkConf:
    "spark.kubernetes.driver.label.app": spark-pi
    "spark.kubernetes.executor.label.app": spark-pi
    "spark.kubernetes.container.image.pullPolicy": Always
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    serviceAccount: spark
    labels:
      version: "1.0"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
    env:
      - name: SPARK_DRIVER_PYTHON
        value: python3
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: "1.0"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
  deps:
    jars: []
  volumes:
    - name: spark-local-dir
      emptyDir: {}
