apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-github
  namespace: kubeflow
spec:
  type: Python
  mode: cluster
  image: gcr.io/spark-operator/spark-py:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: https://raw.githubusercontent.com/reddyprasadaviso/ds-spark-jobs/dev/pi.py
  sparkVersion: 3.1.1
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-controller
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
  executor:
    cores: 1
    instances: 2
    memory: 512m
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL

