apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-python
  namespace: kubeflow
spec:
  type: Python
  mode: cluster
  image: gcr.io/spark-operator/spark-py:v3.1.1   # Python Spark image
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/pi.py
  sparkVersion: 3.1.1
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-controller   # use existing SA in kubeflow
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  executor:
    cores: 1
    instances: 2
    memory: 512m
    securityContext:
      seccompProfile:
        type: RuntimeDefault

